* Emacs Configuration Notes

*** TODO
- Use headline instead of modeline.
- Check ~set-frame-position~ function
- Map =C-`= and =C-~= to shell related command.
- Map Flymake next/prev error
  - Map indent/unindent line key
- Map kill buffer to some more convenient key(such as =M-k= or =S-k=)
- Remap =query-replace=
- Map go next/prev ring in buffer
- Ispell
- =crux-upcase/downcase= also works without selection for one character.
- Fix wired indentations
  - In org-mode, c mode, elisp mode
  
** Keymap
*** Unused keys
- =M-u,l,i,t,j,h,m,q,a,e=
- =C-o,q,z,=
- =C-d,u=
- =S-=
- =C,M-[,],\=  
- =C-M-=
  - =C-M-b= : switch buffer

*** Frequently used commands, but have inconvenient keymap
- =query-replace=: =M-%=
- =scroll-up/down=: ={C,M}-v=
  - to =C-d,u=
- =revert buffer=

*** Consistent key between OS and emacs
- =M-c,v,z= 

** Proposals
*** Quarantine buffers
Sometimes, I'm afraid of killing buffer because

1. The operation may have been a mistake.
2. Maybe I need the buffer later.

So, quarantine buffers can be useful when I want to keep my buffer list clean but also want's to restore qurantined buffers.
The size of the Quarantine buffer list is limited.

*** DefAlias: ~default-yes-sometimes~

#+begin_src emacs-lisp
  (setq original-y-or-n-p 'y-or-n-p)
  (defalias 'original-y-or-n-p (symbol-function 'y-or-n-p))
  (defun default-yes-sometimes (prompt)
    (if (or
         (string-match "has a running process" prompt)
         (string-match "does not exist; create" prompt)
         (string-match "modified; kill anyway" prompt)
         (string-match "Delete buffer using" prompt)
         (string-match "Kill buffer of" prompt)
         (string-match "Kill Dired buffer of" prompt)
         (string-match "delete buffer using" prompt))
        t
      (original-y-or-n-p prompt)))
  (defalias 'yes-or-no-p 'default-yes-sometimes)
  (defalias 'y-or-n-p 'default-yes-sometimes)
#+end_src
